### ISSUE TITLE
[DUB] Configurations not available for latest release v0.9.3

### ISSUE THREAD

**Issue by 9il** [ariovistus/pyd#1]
Available only for "~master".

**Comment by 9il** [comment]
#3 Need special configuration for OS X. This can be done with dub package format.

**Comment by ariovistus** [comment]
do you understand why my configurations aren't showing when dub fetches pyd?

**Comment by 9il** [comment]
Looks like you have created release before the configurations was added to github.

**Comment by ariovistus** [comment]
oh. derp.

**Comment by ariovistus** [comment]
while we're at it, can you get me configurations for osx for python 3.3 and/or 3.4, and for shared libraries? I added a speculative configuration in branch 'develop' for shared libraries for 2.7. Can you build examples/dub/shared_example with it?

**Comment by ariovistus** [comment]
currently stuck on getting a working configuration for windows. once that's figured out, I'll put out a new release.

btw, if you know the answer to this:
http://forum.rejectedsoftware.com/groups/rejectedsoftware.dub/thread/5208/

**Comment by 9il** [comment]
For example, for this configuration you need to specify library path like for OS X:
```
...
        {
            "name": "python33",
            "versions": [
                "Python_2_4_Or_Later",
                "Python_2_5_Or_Later",
                "Python_2_6_Or_Later",
                "Python_2_7_Or_Later",
                "Python_3_0_Or_Later",
                "Python_3_1_Or_Later",
                "Python_3_2_Or_Later",
                "Python_3_3_Or_Later",
            ],
            "libs": ["python3.3m"],
            "lflags-osx": ["-L/Library/Frameworks/Python.framework/Versions/3.3/lib/"],
            "lflags-windows": ["-LPathRelativeToYourProject"],
        },
```
If libs located in `lib` folder in your project than
```
...
            ...
            "lflags-windows": ["-Llib"],
        },
```

**Comment by 9il** [comment]
Please, do not use `.dub` folder for libs. Removing this folder is easy way to reset dub.

**Comment by ariovistus** [comment]
The lib files in question are OMF files generated from lib files distributed with python. Here's how they get generated currently: 
https://pythond.atlassian.net/wiki/display/pyd/2014/12/12/creating+an+omf+lib+file+for+python

And they are in source control (ugh), under infrastructure/windows.

I'd love to get out of having to distribute them, but I don't think dmd can take COFF libraries. Though I did notice recently that optlink has a /IMPLIB flag. I couldn't get it to work, but then come to think of it, that pythonxx.lib must be pointing to a dll somewhere..

**Comment by ariovistus** [comment]
got a working configuration for windows/dmd, got a release out, I think we're good.
