### ISSUE TITLE
compiler selection could be more lenient/helpful

### ISSUE THREAD

**Issue by John-Colvin** [ariovistus/pyd#10]
when building using pydexe I noticed these:

```--compiler=ldc2``` gives the error message 
```error: don't know how to compile C/C++ code on platform 'posix' with 'ldc2' compiler```
whereas it would be nice if it knew that ldc2 is the same as ldc. A better error message would be enough though, so the user knows what's going on.

```--compiler=gdc``` gives the error
```gdc does not support building shared libraries, so python extensions are out of the question```
for some reason build_exe isn't being set

There doesn't appear to be any support for ldmd(2) or gdmd. At the very least it would be good if a more useful error message was given.

**Comment by ariovistus** [comment]
for gdc, you're using python setup.py pydexe?

**Comment by John-Colvin** [comment]
Yes

**Comment by ariovistus** [comment]
probably should add an optional flag --compiler-cmd that would point pyd at a nonstandard executable.
hopefully, this would be sufficient for ldmd and gdmd.

**Comment by John-Colvin** [comment]
I don't understand the distutils patching well enough to fix it, but I think it should be simple to at least redirect `--compiler=ldc2` to `ldc`

**Comment by ariovistus** [comment]
try [alias_ldc2](/ariovistus/pyd/tree/alias_ldc2)

**Comment by ariovistus** [comment]
travis_build fixes the gdc issue (and uncovers a worse one which I can't reasonably fix)
