### ISSUE TITLE
Does PyD 0.13.1 support Python 3.8?

### ISSUE THREAD

**Issue by fccoelho** [ariovistus/pyd#132]
I am get this error message no matter what I do:
```
The sub configuration directive "pyd" -> "python38" references a configuration that does not exist.
```
my package used to build fine on my older ubuntu machine with Python 3.7 (and pyd 0.12.0)

**Comment by ariovistus** [comment]
well, here's me not paying attention. Looking through the api changes now, so far found one or two things that might require fix ups

**Comment by ariovistus** [comment]
3.8 support has been added to master, but i haven't tested it extensively

**Comment by fccoelho** [comment]
Ok I'll give it a try

**Comment by ariovistus** [comment]
0.14.0 has 3.8 support
