### ISSUE TITLE
New release for python3.8 support

### ISSUE THREAD

**Issue by andre2007** [ariovistus/pyd#137]
Since release v0.13.1 support for python 3.8 was added. 
https://github.com/ariovistus/pyd/compare/v0.13.1...master

Could you please create a new release?
Thanks.

**Comment by yazd** [comment]
New release with 3.8 support would be appreciated.

**Comment by fccoelho** [comment]
@ariovistus, any hope for this to be done soon? Can we help in any way? is it simple to add this support for newer versions? I could make a PR...

**Comment by fccoelho** [comment]
By the way I decide to try the version from the master branch and got this error when building:
```bash
fccoelho@fccoelho-MACH-WX9 ~/D/S/corpushashD (master)> dub add-local ~/Downloads/pyd/
Registered package: pyd (version: 0.13.1+commit.5.g93d8235)
fccoelho@fccoelho-MACH-WX9 ~/D/S/corpushashD (master)> dub upgrade pyd
Upgrading project in /home/fccoelho/Documentos/Software_projects/corpushashD
fccoelho@fccoelho-MACH-WX9 ~/D/S/corpushashD (master)> dub build -f
Invalid source/import path: /home/fccoelho/Downloads/pyd/infrastructure/util/
Performing "debug" build using dmd for x86_64.
pyd 0.13.1+commit.5.g93d8235: building configuration "python38"...
corpushashd 0.3.2: building configuration "application"...
Linking...
Invalid source/import path: /home/fccoelho/Downloads/pyd/infrastructure/util/
```

am I missing some key step in the build?

**Comment by fccoelho** [comment]
the path `pyd/infrastructure/util/` does not exist, but `pyd/infrastructure/pyd/util/` does... 
So maybe this needs to be fixed...

**Comment by ariovistus** [comment]
curious. i renamed util/ to pyd/util recently and thought I got everything.

**Comment by ariovistus** [comment]
So there are a couple minor issues that make me hesitant to make a release. the first is the test suite is failing on a linker test that suggests the deimos headers are off somewhere for 3.8. which might not be a big deal.
The second is the .lib files in infrastructure/windows. I have forgotten how to generate them. They are necessary for linking to python.dll or whatever on x86 windows with dmd.

**Comment by andre2007** [comment]
@ariovistus if you can find out the details about the lib files you might use github Actions for the compilation. Therefore it is documented and done automatically for further releases.

**Comment by ariovistus** [comment]
ok, sorta remember it now, there's a tool called implib. left some notes at https://pythond.atlassian.net/wiki/spaces/pyd/pages/edit-v2/1784578049?
But something seems to have changed since the last time i did this, symbols that used to be _PyTuple_Size are now PyTuple_Size. I imagine the windows python compile is different somehow, but i wouldn't know where to start.
somewhat tempted to deprecate 32bit python/windows/dmd.

**Comment by fccoelho** [comment]
+1 to deprecate 32bit python/windows/dmd.

**Comment by andre2007** [comment]
Thanks for the new release.

**Comment by fccoelho** [comment]
Thanks! I have rebuilt my projects for Python38 without problems!
