### ISSUE TITLE
support vibe.data.json.Json

### ISSUE THREAD

**Issue by ariovistus** [ariovistus/pyd#14]
as requested by @Lord-Evil

will put this in an extension library, but pyd needs to at least not break itself when passed a Json object.

**Comment by ariovistus** [comment]
Current problem is assert(!isInputRange!Json) fails even though Json is not designed to be an input range, which causes range_wrapper to break, which causes builds to fail. I guess we could put range_wrapper inside a __traits(compiles) check, but this is more of a problem with Json or isInputRange. Or both.

**Comment by ariovistus** [comment]
cf rejectedsoftware/vibe.d#634

**Comment by ariovistus** [comment]
done in 0.9.7 and https://github.com/ariovistus/vibe.pyd and on code.dlang.org in vibe-pyd

**Comment by Lord-Evil** [comment]
Yay! Thanks))))
