### ISSUE TITLE
Is this a right approach?

### ISSUE THREAD

**Issue by Lord-Evil** [ariovistus/pyd#15]
```
PydObject my_import(string name) {
    debug assert(Py_IsInitialized(), "python not initialized");
    auto list=new PydObject(PyImport_GetModuleDict());
    if(list.has_key(name))
        return new PydObject(PyImport_ReloadModule(PyImport_AddModule(zcc(name))));
    else
        return new PydObject(PyImport_ImportModule(zcc(name)));
}
```

The idea behind this is that scripts are loaded dynamically when certain command received, and if it fails then we can fix script's code without restarting the "kernel".

**Comment by Lord-Evil** [comment]
Seems like I've got a problem with this... Might need your help to solve it. I'll try to debug first.

**Comment by Lord-Evil** [comment]
I've managed it. The problem was that imports are global and I had been trying to run them as "stand alone scripts" having globals in them, and it's all got messed up between two separate contexts (for two different users). Resoled like this:
```
InterpContext loadScript(string modName){
	auto script = new InterpContext;
	try{
		script.py_stmts("import os, sys");
		script.py_stmts("sys.path.append(os.getcwd())");
		script.py_stmts("sys.path.append(os.getcwd()+'/"~scriptHome~"/')");//for loading extra modules
		script.mod=my_import(scriptHome~"."~modName);
		script.error="";
	}catch(Exception e){
		logInfo("Importing script failed!");
		logInfo(e.msg);
		script.error=e.msg;
	}
	return script;
}
........
InterpContext script;
script = loadScript(sc.moduleName);
script.comm=script.py_eval("mod.Interface()");
script.cmd=command;
script.py_stmts("comm.command(cmd)");
```
This way separate sessions do not get mixed up :)))

**Comment by ariovistus** [comment]
nice. but this line 

    script.py_stmts("sys.path.append(os.getcwd()+'/"~scriptHome~"/')");

is making me twitch (xss vuln)

**Comment by Lord-Evil** [comment]
Is there a better way to add path to global python system vars?

**Comment by ariovistus** [comment]
script.scriptHome = scriptHome;
    script.py_stmts("sys.path.append(os.getcwd()+ scriptHome)");

or somesuch

**Comment by Lord-Evil** [comment]
Thx, fixed :)
