### ISSUE TITLE
what's needed to suport python3.9? no module named '_contextvars' ?

### ISSUE THREAD

**Issue by mw66** [ariovistus/pyd#154]
Ubuntu 21.04's default python version is: Python 3.9.4

I try to make pyd work with python3.9,

I just copy the configuration python38 section of `~/.dub/packages/pyd-0.14.0/pyd/dub.json`, and make modification for python3.9

then, I build a simple project using 
```
        "subConfigurations": {                                                                                                                             
                "pyd": "python39"                                                                                                                          
        },       
```

the build is fine, but when I run it: it error out: no module named '_contextvars'.

I'm wondering how to make python3.9 work?

**Comment by mingwugmail** [comment]
update:

using the Ubuntu's default python i.e. `/usr/bin/python3.9' seems worked.

**Comment by neel-bp** [comment]
can you please share what modifications you applied? thanks.

**Comment by fccoelho** [comment]
Sense of "deja vu" here... every time a new Python version is out, everything breaks

**Comment by mw66** [comment]
This is working now:

https://github.com/ariovistus/pyd/commit/63de090d705b39624aa3d735105e4d14e251911e
