### ISSUE TITLE
Missing linker flags: OS X, ldc

### ISSUE THREAD

**Issue by John-Colvin** [ariovistus/pyd#18]
I just tried to compile the ```hello``` example on OS X and it works find with dmd, but with ldc it doesn't seem to be linking with python:

dmd link command:

```dmd -shared -L/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/config-3.4m/libpython3.4m.a -debug -ofbuild/lib.macosx-10.10-x86_64-3.4/hello.so build/temp.macosx-10.10-x86_64-3.4/infra/temp.o build/temp.macosx-10.10-x86_64-3.4/infra/so_ctor.o```

ldc link command:
```ldc2 -shared -d-debug -of build/lib.macosx-10.10-x86_64-3.4/hello.so build/temp.macosx-10.10-x86_64-3.4/infra/temp.o```

**Comment by ariovistus** [comment]
I assume this is with the distutils build? I suppose dub doesn't work any better after @9il fixed it up..

I don't have access to a OS X box, what to do what to do.

**Comment by 9il** [comment]
[dub.json](https://github.com/ariovistus/pyd/blob/master/dub.json) dose not have any common/posix/osx fields with compiler specification. So, it is DUB bug.

**Comment by John-Colvin** [comment]
This is with distutils. Dub didn't work either, but that's a separate bug I'll file/fix later
