### ISSUE TITLE
[OS X][DMD 2.066] Error: undefined identifier mach_port_t

### ISSUE THREAD

**Issue by 9il** [ariovistus/pyd#2]
../../.dub/packages/pyd-master/infrastructure/pyd/thread.d(117): Error: undefined identifier mach_port_t

**Comment by ariovistus** [comment]
seriously? aws can't host osx and travis won't either? Boo.

**Comment by 9il** [comment]
Travis can host OS X someway, but linux is default.

**Comment by ariovistus** [comment]
http://blog.travis-ci.com/2014-05-13-multi-os-feature-available/

says they aren't accepting  requests

**Comment by ariovistus** [comment]
see if develop fixes this
