### ISSUE TITLE
DateTime

### ISSUE THREAD

**Issue by Laeeth** [ariovistus/pyd#21]
Worth writing a cython shim (I guess one could do in C/D via the Python API, but I wouldn't know how) to convert D DateTimes back and forth between Python datetime (and ideally numpy datetime64 too)?  Particularly useful for pydmagic where often in Jupyter the first thing you do is import a text file...  with dates in it.

**Comment by Laeeth** [comment]
module example;
import std.datetime;
import std.stdio;
import pyd.pyd;
import std.conv;
import deimos.python.datetime;


DateTime foo()
{
    return DateTime(1999,1,1);
}
extern(C) void PydMain() {
    ex_d_to_python((DateTime dt) => PyDateTime_FromDateAndTime(dt.year,dt.month,dt.day,dt.hour,dt.minute,cast(int)dt.second,0));
    def!foo();
    module_init();
    PyDateTime_IMPORT();
}

Ideally, shouldn't PyD do this for you ?

**Comment by ariovistus** [comment]
It probably should. following your conversation at http://forum.dlang.org/thread/dehleaecsihenaapyqhl@beta.forum.dlang.org,

it sounded like there was some concern about python's datetime has fractions of a second and std.DateTime doesn't, and something about timezones.

**Comment by ariovistus** [comment]
For python -> D, you have to specify the result type you want, so you deserve to lose milliseconds if you asked for a std.DateTime.

**Comment by ariovistus** [comment]
We probably want:

std.DateTime <-> datetime.datetime
std.SysTime <-> datetime.datetime
std.TimeOfDay <-> datetime.time
std.Date <-> datetime.date
std.Date <- datetime.datetime
std.DateTime, std.SysTime <- datetime.date

also,
std.DateTime, std.SysTime, std.Date, std.TimeOfDay <- numpy.datetime64

going the other way is going to require a custom conversion function with pyd's current design.
don't know how troublesome this will be for your use case.

I don't suppose you could write up some example code for your use case? That would be handy for the test suite..

**Comment by Laeeth** [comment]
Below sounds great, and v thoroughly specified (unlike my original attempt).

One question about custom conversion: I think it's fine to require that, but I didn't find it so easy before until I got my hands dirty with Python C API.  Ended up in my first attempt at using embedded Python to make a datetime.datetime.  So can you think of an easy way to make a numpy datetime64 efficiently from D ?  I will look at the API and source when time.  Ie not having it be automatic is one thing - so you have to call

PyObject* asNpDatetime64(SysTime sysTime)

But if that were built into PyD that might be nice.  Will have a see.

I don't know how to say this, but I don't use D datetimes myself ;) except for something quick.  Main reason is that I want to know the binary representation and I also know that if there is strange behaviour it is my fault.  But the functionality required is the same as far as PyD goes, and these are sensible defaults.

I will write some example code, but might be a little while.


Laeeth

**Comment by Laeeth** [comment]
This was the monstrosity of my first attempt to make a datetime in D!

	version(PyD)
	{
		import pyd.pyd;
		import pyd.embedded;
		PydObject toPyD()
		{
			alias dt=this;
			auto context = new InterpContext();
			context.py_stmts("import datetime");
			return context.py_eval("datetime.datetime("~to!string(dt.year)~","~to!string(dt.month)~","~to!string(dt.day)~","~
				to!string(dt.hour)~","~to!string(dt.minute)~","~to!string(dt.second)~")");
		}
	}

**Comment by ariovistus** [comment]
this is mostly done, except for timezone support (outstanding #51), so yeah
