### ISSUE TITLE
interpcontext is broken for 2.068 i think due to deprecation -> gone for object.clear

### ISSUE THREAD

**Issue by Laeeth** [ariovistus/pyd#23]
http://dlang.org/deprecate.html#clear

/home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/util/multi_index.d(4900): Error: undefined identifier 'clear' in module 'object'

clear
Call an object's destructor.

auto a = new Class();
clear(a);
Corrective Action
Use object.destroy() instead.

auto a = new Class();
destroy(a);

====
it 'works' (seems to)  if you change line 4900 to object.destroy, but I don't yet understand the codebase.

**Comment by ariovistus** [comment]
that ought to be the right fix. sending it through: ariovistus/multi_index@a5dc82376376716e95631a114d281f4b2de21217

**Comment by Lord-Evil** [comment]
Umm.. that's multi_index repo. Not sure, what else you did that've missed, but todays pyd pull compile fails right on the same spot.

**Comment by John-Colvin** [comment]
https://github.com/ariovistus/pyd/pull/26

**Comment by ariovistus** [comment]
ya sorry, started it but then got distracted and haven't had time lately
