### ISSUE TITLE
gdc can't compile multi_index

### ISSUE THREAD

**Issue by ariovistus** [ariovistus/pyd#42]
/tmp/ccZ8LnGz.s: Assembler messages:

/tmp/ccZ8LnGz.s:131179: Error: symbol `_D4util11multi_index276__T19MultiIndexContainerTC4core6thread6ThreadTS4util11multi_index127__T9IndexedByS1094util11multi_index89__T6HashedVbi0VAyaa1_61VAyaa21_7479706569642861292e6765744861736828266129VAyaa4_613d3d62ZZ9IndexedByTS4util11multi_index15MallocAllocatorTS4util11multi_index11MutableViewZ19MultiIndexContainer6index08containsMxFC4core6thread6ThreadZb' is already defined

error: command 'gdc' failed with exit status 1

means gdc can't compile pyd. :(

**Comment by ariovistus** [comment]
https://issues.dlang.org/show_bug.cgi?id=15324

**Comment by ibuclaw** [comment]
Nope, unrelated.  Different linker error in the bug report.

**Comment by jpf91** [comment]
@ariovistus does this still happen with a very recent GDC (from one of the github branches, the binary downloads are not updated yet)? We recently changed how we deal with duplicated template symbols from the frontend.

If this is an example of the frontend sending template instances multiple times to the backend, this should work fine now. If this is similar to DMD issue 15324, i.e. you actually do have duplicated symbols, probably via function overloads with aliases, then this is an issue in the pyd code.

**Comment by ariovistus** [comment]
gdc 6.3.0 can compile pyd
