### ISSUE TITLE
missing python35_digitalmars.lib

### ISSUE THREAD

**Issue by John-Colvin** [ariovistus/pyd#50]

**Comment by ariovistus** [comment]
grr linker issues

**Comment by majiang** [comment]
Looking at the [directory](https://github.com/ariovistus/pyd/tree/master/infrastructure/windows), indeed it's missing. When I changed `subConfiguration` from `"pyd": "python35"` to `"pyd": "python34"` it compiled (but did not run currently).

**Comment by ariovistus** [comment]
fixed
