### ISSUE TITLE
setup.py doesn't mention Python 3.5 

### ISSUE THREAD

**Issue by russel** [ariovistus/pyd#56]

**Comment by ariovistus** [comment]
and it won't until I can get the lib file for dmd built. need to devote some time to figuring out why I can't seem to do that anymore

**Comment by dejlek** [comment]
Can I help somehow?

**Comment by ariovistus** [comment]
smack me upside the head, maybe. Turns out I've been trying to build with 64 bit python all this time.

**Comment by ariovistus** [comment]
Actually, the changes in the python headers in 3.5 and 3.6 need to be incorporated into deimos. I probably won't have time in the immediate future to do it.
