### ISSUE TITLE
Getting: ImportError: DLL load failed: %1 is not a valid Win32 application when calling D from Python via PyD

### ISSUE THREAD

**Issue by vasudevram** [ariovistus/pyd#59]
I followed the steps here:

http://pyd.readthedocs.io/en/latest/extend.html

I created a new dub project using dub init test_pyd.

Then edited the dub.json file that was created, to include PyD as a dependency, 
according to the syntax shown here:

https://code.dlang.org/packages/pyd

The complete dub.json file after the edit:
{
    "name": "test_pyd",
    "authors": [
        "user"
    ],
    "description": "A test of PyD",
    "copyright": "Copyright 2016, user",
    "license": "proprietary",
    "dependencies": {
        "pyd": "~>0.9.8"  
    }
}
Then I did: dub
which built the library test_pyd.lib okay and gave a message saying so.

Then I created the setup.py shown at the above PyD docs URL, and ran it (after git cloning the PyD repo to local:

$ python setup.py install

This went through okay with no errors, and showed that it had done this

copying build\lib.win-amd64-2.7\hello.pyd -> C:\Python2711\Lib\site-packages

Then created a file test_pyd.py with this content:

import hello
hello.hello()

But when I run it with:

python test_pyd.py

I get this error:

Traceback (most recent call last):
  File "test_pyd.py", line 2, in <module>
    import hello
ImportError: DLL load failed: %1 is not a valid Win32 application.

Thanks for any debugging suggestions you can provide.

**Comment by ariovistus** [comment]
I'm thinking pyd doesn't support 64 bit windows builds. Seems like walter set up linking differently there and I never got around to ensuring pyd can handle it.

**Comment by vasudevram** [comment]
Thanks for the reply. 

I was on 64 bit Windows. The DMD compiler used was 32 bit, I think. But did not check when opening thiis  issue, whether I used 32 bit Python 2.7 or 64 bit Python 3.5. Will check some more and then reply if needed.

**Comment by ariovistus** [comment]
assuming OP was using 64 bit python
