### ISSUE TITLE
Error instantiating

### ISSUE THREAD

**Issue by fccoelho** [ariovistus/pyd#68]
I I am trying to wrap a class and I am following the example from wrap.

this is the extern block I am using:

```d
extern(C) void PydMain() {
    alias document = dstring[];
    def!(get_salt)();
    wrap_class!(
            HashCorpus,
            Init!(document[], string, string, string, uint),
            )();
    module_init();
}
```

this is the compilation error I am getting:

```
/usr/local/lib/python3.5/dist-packages/pyd/infrastructure/pyd/class_wrap.d(526): Error: tuple index 0 exceeds 0
/usr/local/lib/python3.5/dist-packages/pyd/infrastructure/pyd/class_wrap.d(534): Error: template instance pyd.class_wrap.Init!(dstring[][], string, string, string, uint).Init.Inner!(HashCorpus) error instantiating
/usr/local/lib/python3.5/dist-packages/pyd/infrastructure/pyd/make_wrapper.d(127):        instantiated from here: shim!(0LU, HashCorpus)
/usr/local/lib/python3.5/dist-packages/pyd/infrastructure/pyd/make_wrapper.d(137):        instantiated from here: class_decls!(0u, HashCorpus, Init!(dstring[][], string, string, string, uint))
/usr/local/lib/python3.5/dist-packages/pyd/infrastructure/pyd/class_wrap.d(1483):        instantiated from here: make_wrapper!(HashCorpus, Init!(dstring[][], string, string, string, uint))
/usr/local/lib/python3.5/dist-packages/pyd/infrastructure/pyd/class_wrap.d(1476):        instantiated from here: _wrap_class!(HashCorpus, "HashCorpus", "", "", Init!(dstring[][], string, string, string, uint))
source/corpushash/hashers.d(207):        instantiated from here: wrap_class!(HashCorpus, Init!(dstring[][], string, string, string, uint))

```

**Comment by ariovistus** [comment]
which compiler are you using?

**Comment by fccoelho** [comment]
dmd

**Comment by fccoelho** [comment]
It is worth mentioning that if I comment out the `wrap_class!(...` line. it compiles without error.

**Comment by ariovistus** [comment]
which version?

**Comment by fccoelho** [comment]
DMD64 D Compiler v2.074.0

**Comment by ariovistus** [comment]
Looks like the first issue is it's supposed to be printing out an error like

Error: static assert  "HashCorpus: Cannot find constructor with params (dstring[][], string, string, string, uint)"

but the compiler evaluates the tuple dereference first.

What does your HashCorpus look like?

**Comment by fccoelho** [comment]
the source is [here](https://github.com/fccoelho/corpushashD/blob/master/source/corpushash/hashers.d)

**Comment by fccoelho** [comment]
the version in the gh repo above does not contain the extern, I am trying to make it work in my local repo, before I push to GH.

**Comment by ariovistus** [comment]
for some reason, the compiler thinks the signature of your constructor is
(dstring[][], string, string, string, const(uint)), and I have a feeling Init isn't very smart about comparing that.

**Comment by fccoelho** [comment]
What would be a good way to work around this issue?

**Comment by ariovistus** [comment]
try changing your Init param from uint to const(uint)

**Comment by fccoelho** [comment]
It worked! but not with const(uint) but like this:

```D
extern(C) void PydMain() {
    alias document = dstring[];
    module_init();
    def!(get_salt)();
    wrap_class!(HashCorpus,
            Property!(HashCorpus.corpus),
            Property!(HashCorpus.corpus_path),
            Property!(HashCorpus.encoding),
            Property!(HashCorpus.hash_function),
            Property!(HashCorpus.salt_length),
            Init!(document[], string, string, string, const uint),
            )();
}
```

thanks!

**Comment by fccoelho** [comment]
By the way, how did you figure out the compiler was expecting a `const`? That information was not in the compillation error message.

**Comment by ariovistus** [comment]
Init reflects on all the constructors in the class in question. it's quite easy to print out what it sees.

Something like

```
alias Overloads = TypeTuple!(__traits(getOverloads, HashCorpus, "__ctor"));
pragma(msg, ParameterTypeTuple!(Overloads[0]).stringof);
```
I will change pyd to output this information when this situation.
