### ISSUE TITLE
Dub repository is out-of-date

### ISSUE THREAD

**Issue by Hackerpilot** [ariovistus/pyd#85]
https://code.dlang.org/packages/pyd

For some reason dub is only aware of the 0.9.x series of releases. Those releases lack compatability with python 3.6, which I think is the default on Ubuntu 18.4. (That release of Ubuntu doesn't have packages for python 3.5) Is there a way to get code.dlang.org to refresh its cache of available versions?

A temporary workaround is to specify `~master` as the version to use.

**Comment by ariovistus** [comment]
https://github.com/dlang/dub-registry/issues/269

**Comment by John-Colvin** [comment]
@ariovistus have you tried logging in to code.dlang.org and triggering a manual update?

**Comment by ariovistus** [comment]
yup, that was it

**Comment by ariovistus** [comment]
code.dlang.org is up to date
